name: ubuntu

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number }}-${{ github.event.ref }}
  cancel-in-progress: true

on: [push, pull_request]

permissions:
  contents: read

jobs:
  build:
    # Please try to use as many packages as possible from Ubuntu APT repos,
    # and as few as possible from PyPI,
    # as the purpose here is to test against system packages.
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        submodules: true
    - name: Install APT packages
      run: |
        sudo apt-get update
        sudo apt install -y \
          libhdf5-dev libblosc-dev libblosc2-dev libbz2-dev liblz4-dev \
          liblzo2-dev libsnappy-dev libzstd-dev zlib1g-dev \
          python3-all-dev python3-pip python3-build python3-setuptools cython3 \
          python3-numpy python3-packaging python3-cpuinfo python3-numexpr \
          python3-typing-extensions \
          python3-pytest python3-pytest-doctestplus \
          python3-sphinx python3-sphinx-rtd-theme python3-numpydoc python3-ipython \
          latexmk texlive-fonts-recommended texlive-latex-recommended \
          texlive-latex-extra texlive-plain-generic
    - name: Build PyTables
      run: make build
      env:
        PYTABLES_NO_EMBEDDED_LIBS: TRUE
    - name: Build HTML documentation
      run: make html
    - name: Build LaTeX documentation
      run: make latex
    - name: Source distribution
      run: make dist
    - name: Test
      run: make check
